### PR TITLE
update justify function using textwrap

### PR DESCRIPTION
**Pull request by gforsyth**
Hey @adqm!  I had time to kill on a red-eye and simplified the `justify` function -- let me know if it doesn't work as you expect.

### CODE REVIEW

**Comment by adqm** [comment]
Thanks!  I had tried something like this in my branch, but couldn't make it work.  Using `textwrap`, I get weird whitespace-related issues.  It has a lot of extra whitespace (notice between "python names," and "and" on the second line) and some of the lines seem to go farther than 80 characters...

```
Registered Completer Functions: 
  'python_mode' :      Python-mode completions for @( and ${
         'base' : If the line is empty, complete based on valid commands, python names,     and
                  paths.  If we are completing the first argument, complete
                  based on     valid commands and python names.
         'skip' :      Skip over several tokens (e.g., sudo) and complete based on the rest of the
                  line.
           'cd' :      Completion for "cd", includes only valid directory names.
        'rmdir' :      Completion for "rmdir", includes only valid directory names.
         'bash' : Completes based on results from BASH completion.
          'man' : Completes an option name, based on the contents of the associated man     page.
       'import' :      Completes module names and contents for "import ..." and "from ... import
                  ..."
       'python' :      Completes based on the contents of the current Python environment,     the
                  Python built-ins, and xonsh operators.
         'path' : Completes based on a path name.
```

With mine, I get what I consider to be nicer output:

```
Registered Completer Functions: 
  'python_mode' : Python-mode completions for @( and ${
         'base' : If the line is empty, complete based on valid commands, python
                  names, and paths. If we are completing the first argument,
                  complete based on valid commands and python names.
         'skip' : Skip over several tokens (e.g., sudo) and complete based on the
                  rest of the line.
           'cd' : Completion for "cd", includes only valid directory names.
        'rmdir' : Completion for "rmdir", includes only valid directory names.
         'bash' : Completes based on results from BASH completion.
          'man' : Completes an option name, based on the contents of the
                  associated man page.
       'import' : Completes module names and contents for "import ..." and "from
                  ... import ..."
       'python' : Completes based on the contents of the current Python
                  environment, the Python built-ins, and xonsh operators.
         'path' : Completes based on a path name.
```

**Comment by gforsyth** [comment]
Ok, I think this works well now.  Replaced the per-docstring calculated padding with some string formatting goodness and standardized the completer docstrings (so one liners are on one line, but everything else lives on separate lines from the `'''` wrappers)

**Comment by adqm** [comment]
> and standardized the completer docstrings (so one liners are on one line, but everything else lives on separate lines from the ''' wrappers)

Just out of curiosity: is this necessary for things to be formatted properly, or just something that makes them look nicer in the source?  I think I'd like to avoid restricting docstrings of user-defined completers in this way.

**Comment by adqm** [comment]
Otherwise, definitely looks good to me!  Thanks!

**Comment by adqm** [comment]
Okay, just did some testing.  Looks good to me; thanks for the help!

**Comment by gforsyth** [comment]
It's in PEP8, but not a huge deal. It was responsible for the initial weird
whitespace issues but the split/join should stop it from having any effect
moving forward

**Pull request merged**
